global:
  scrape_interval: 25s
  scrape_timeout: 20s
  evaluation_interval: 25s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
        - "localhost:9093"
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - telegraf:9126
